name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
   MONGO_URI: mongodb+srv://${{ vars.MONGO_USERNAME }}:${{ secrets.MONGO_PASSWORD }}@cluster0.vhiyod5.mongodb.net/superdata?authSource=admin&replicaSet=atlas-g26qft-shard-0&retryWrites=true&w=majority&ssl=true
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                node-version: [18, 19, 20]
                operating-system: [ubuntu-latest, macos-latest]
                exclude:
                    - node-version: 18
                      operating-system: macos-latest
        runs-on: ${{ matrix.operating-system }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
        
        - name: Archive Test Results
          uses: actions/upload-artifact@v3
          with:
            name: test-results
            path: test-results.xml
          
   
            